# Generated by Django 4.2.23 on 2026-03-31 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Demirbaş Kodu')),
                ('internal_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dahili Kod')),
                ('inventory_item', models.CharField(blank=True, max_length=255, null=True, verbose_name='İngilizce Ad (Inventory Item)')),
                ('turkish_name', models.CharField(max_length=255, verbose_name='Malzeme Adı (Turkish Name)')),
                ('campus', models.CharField(max_length=100, verbose_name='Yerleşke')),
                ('floor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kat')),
                ('room', models.CharField(max_length=100, verbose_name='Oda / Bölüm')),
                ('category', models.CharField(max_length=100, verbose_name='Kategori')),
                ('status', models.CharField(max_length=100, verbose_name='Durum')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Renk')),
                ('date', models.DateField(verbose_name='Kayıt Tarihi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='Görsel')),
            ],
            options={
                'verbose_name': 'Demirbaş',
                'verbose_name_plural': 'Demirbaşlar',
                'ordering': ['-date'],
            },
        ),
    ]
