# Generated by Django 4.2.23 on 2026-03-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Kayıt Tarihi'),
        ),
    ]
